- type: gameMapPool
  id: DefaultMapPool
  maps:
    - Amber
    - Bagel
    - Box
    - Convex
    - Elkridge
    - Fland
    - Marathon
    - Oasis
    - Packed
    - Plasma
    - Prime # Harmony
    - Reach
    - Exo